language: python
dist: trusty

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=lint

install:
  - pip install tox

before_script:
# Install chromedriver - https://sites.google.com/a/chromium.org/chromedriver/
# This is not provided by Travis, but is needed by Selenium
  - wget -N http://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - sudo mv chromedriver /usr/bin

# Make chrome available as "chrome"
  - sudo ln -s /usr/bin/google-chrome-stable /usr/bin/chrome

  - echo "Using chrome version $(chrome --version) from $(which chrome)"
  - echo "Using chromedriver version $(chromedriver --version) from $(which chromedriver)"

script:
  - export SPLINTER_WEBDRIVER=chrome
  - export TRAVIS=true
  - tox -e $TOXENV
